import{a as m,i,S as p}from"./assets/vendor-D_Kruy52.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const f=async(o,r=1)=>{const a="https://pixabay.com/api/";try{return(await m.get(a,{params:{key:"48797096-f4883239ab22667ebb957e7d3",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:9}})).data.hits}catch(s){throw console.error("Error fetching images:",s),s}},d=o=>{const r=document.querySelector(".loader");r&&r.classList.toggle("hidden",!o)},g=o=>{const r=document.querySelector(".gallery");if(!o){i.error({message:"Please enter a search term!",position:"topRight",timeout:5e3,transitionIn:"fadeIn",transitionOut:"fadeOut"});return}if(o.length===0){i.error({message:"Sorry, no images match your search. Please try again!",position:"topRight",timeout:5e3,transitionIn:"fadeIn",transitionOut:"fadeOut"});return}r.innerHTML="";const a=o.map(({webformatURL:s,largeImageURL:e,tags:t,likes:n,views:c,comments:l,downloads:u})=>`
      <li>
        <a href="${e}" class="gallery-item">
          <img src="${s}" alt="${t}" />
        </a>
        <div class="info">
          <div class="stat-item"><p class="label">Likes</p><p class="value">${n}</p></div>
          <div class="stat-item"><p class="label">Views</p><p class="value">${c}</p></div>
          <div class="stat-item"><p class="label">Comments</p><p class="value">${l}</p></div>
          <div class="stat-item"><p class="label">Downloads</p><p class="value">${u}</p></div>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",a)};document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".gallery"),r=document.querySelector(".form"),a=document.querySelector(".form-input");!r||!a||r.addEventListener("submit",async s=>{s.preventDefault();const e=a.value.trim();if(!e){i.error({message:"Sorry, no images match your search. Please try again!",position:"topRight",timeout:2e3,transitionIn:"fadeIn",transitionOut:"fadeOut"});return}o.innerHTML="",d(!0);try{const t=await f(e);if(t.length===0){i.error({message:"Sorry, no images match your search. Please try again!",position:"topRight",timeout:2e3,transitionIn:"fadeIn",transitionOut:"fadeOut"});return}await new Promise(u=>setTimeout(u,2e3)),g(t);const n=new p(".gallery a");n.refresh();const c=document.querySelector(".next-btn"),l=document.querySelector(".prev-btn");c&&c.addEventListener("click",()=>{n.next()}),l&&l.addEventListener("click",()=>{n.prev()})}catch(t){i.error({message:"Something went wrong, please try again later.",position:"topRight",timeout:2e3,transitionIn:"fadeIn",transitionOut:"fadeOut"}),console.error("Error fetching images:",t)}finally{d(!1)}},{passive:!1})});
//# sourceMappingURL=index.js.map
